# -*- coding: utf-8 -*-
"""SalariosDS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NKO8yv-h7HEHDdFw1FBQZit4KL_vUhTp
"""

#Importamos librerias con las que se va a trabajar
import pandas as pd
import matplotlib.pyplot as plt

#Carga del archivo
datos = pd.read_csv('datasets/salarios.csv')

#Imprimimos primeras 5 filas
print(datos.head(5))

# Consulta: Mostrar la cantidad total de registros en el DataFrame
total_registros = len(datos)
print("Cantidad total de registros:", total_registros)

#Conocemos las columnas
datos.columns

#Obtenemos Información del DataSet
datos.info

"""  Cálculo de métricas"""

# Calcular la media del salario
media_salario = datos['salario_en_dolares'].mean()

# Calcular la mediana del salario
mediana_salario = datos['salario_en_dolares'].median()

# Calcular el salario máximo
max_salario = datos['salario_en_dolares'].max()

# Calcular el salario mínimo
min_salario = datos['salario_en_dolares'].min()

# Calcular la desviación estándar del salario
std_salario = datos['salario_en_dolares'].std()

# Mostrar las métricas calculadas
print("Métricas de salario en dolares en un año de trabajo:")
print("Media del salario:", media_salario)
print("Mediana del salario:", mediana_salario)
print("Salario máximo:", max_salario)
print("Salario mínimo:", min_salario)
print("Desviación estándar del salario:", std_salario)

#Datos por experiencia
datos.loc[datos.experiencia=='Semi Senior']

#Filtrado de ddatos por experiencia y Titulo
datos_filtrados = datos[(datos.experiencia =='Semi Senior')&(datos.posicion=='Cientifico de datos')]
datos_filtrados.head(5)

#Agrupamos datos
agrupados = datos.groupby(['experiencia', 'posicion']).salario_en_dolares.agg([min,max])
print(agrupados)


#Ordenar por salarios en orden descendente
salarios_ordenados = datos.sort_values(by="salario_en_dolares", ascending=False)

#Mostrar los cinco salarios mas altos
salarios_mas_altos = salarios_ordenados.head(5)
print(salarios_mas_altos)

#Graficamos los datos de experiencia y salario
datos_orden = datos.sort_values('salario_en_dolares', ascending=False)
plt.bar(datos_orden['experiencia'], datos_orden['salario_en_dolares'])
plt.xlabel('Experiencia')
plt.ylabel('Salario')
plt.title('Salario por experiencia')
plt.show()

# Gráfico de barras: Salario por posición
plt.figure(figsize=(10, 6))
plt.bar(datos['posicion'], datos['salario_en_dolares'])
plt.xlabel('Posición')
plt.ylabel('Salario_en_dolares')
plt.title('Salario por posición')
plt.xticks(rotation=90)
plt.show()

# Diagrama de caja: Salario por modalidad
plt.figure(figsize=(8, 6))
plt.boxplot([datos[datos['esquema'] == 'Presencial']['salario_en_dolares'],
             datos[datos['esquema'] == 'Hibrido']['salario_en_dolares'],
             datos[datos['esquema'] == 'Remoto']['salario_en_dolares']],
            labels=['Presencial', 'Híbrido', 'Remoto'])
plt.xlabel('Presencialidad')
plt.ylabel('Salario en dolares')
plt.title('Salario por presencialidad')
plt.show()
